#!/usr/bin/env bash

# set as VDA for testing in case that real adapter won't start because of unknown reason

export LOG_FILE=/tmp/qvscdbg.log
echo $LOG_FILE
echo `date` >> $LOG_FILE
echo "Test adapter started: $0 $1 $2 $3 $4 $5 $6 $7 $8 $9" >> $LOG_FILE